spring.profiles.active: dev

security.oauth2.resource.filter-order: 3
security.signing-key: MaYzkSjmkzPC57L
security.encoding-strength: 256
security.security-realm: Spring Boot JWT Example

spring.application.name: jwt-springBoot-oauth
spring.jpa.hibernate.ddl-auto: update